name: atomic_x_core_example
description: "LiveKit AtomicXCore API Example - Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  atomic_x_core: ^4.0.0
  crypto: ^3.0.6
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3
  svgaplayer_flutter: ^2.2.0
  cached_network_image: ^3.3.1
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true

  uses-material-design: true
